### ISSUE TITLE
KeyError: 'Slave_IO_Running'

### ISSUE THREAD

**Issue by LeotLiu** [ddcw/inspection#2]
请教遇到的问题，版本是2.2的，采集数据和生成报告得分开的场景，已经在远程服务器用coll_data.sh取得xml数据，但是生成报告时遇到以下错误：
$ ./ddcw_inspection -a 192.168.26.30_3300_20220921_112610.xml
开始分析采集数据, 并生成巡检报告
Process Process-2:
Traceback (most recent call last):
  File "pandas/core/indexes/base.py", line 2898, in get_loc
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Slave_IO_Running'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "inspection/work_inspection.py", line 264, in inspection
  File "<string>", line 1, in <module>
  File "inspection/anadata.py", line 298, in slave_info
  File "inspection/anadata.py", line 56, in __inner_function_3
  File "pandas/core/frame.py", line 2906, in __getitem__
  File "pandas/core/indexes/base.py", line 2900, in get_loc
KeyError: 'Slave_IO_Running'
巡检完成. 巡检报告如下:
192.168.26.30:3300 巡检失败, 请查看日志

运行后没有任何报告输出。

**Comment by ddcw** [comment]
看起来是主从的问题,  请看下日志呢(默认路径: logs/inspection.log)

**Comment by ddcw** [comment]
如果确定只有这个报错的话, 可以选择不巡检主从信息,  修改方法如下:
编辑配置文件conf/inspection.yaml  在  object_name : 'slave_info' 下面添加 enabled : False

**Comment by LeotLiu** [comment]
> 看起来是主从的问题, 请看下日志呢(默认路径: logs/inspection.log)

[2022-09-21 16:08:48] [INFO]    [8827] 开始读取固定采集项
[2022-09-21 16:08:48] [INFO]    [8827] 开始巡检
[2022-09-21 16:08:48] [INFO]    [8827] 巡检no_primary_key (无主键的表)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检redundant_indexes (冗余索引)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检unused_indexes (未使用的索引)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检full_table_scans (全表扫描的表)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检auto_increment_columns (自增键使用率)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检special_column (特殊字段)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检big_table (大表)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检cold_table (冷表)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检partition_table (分区表)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检is_nullable (可为空的字段)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检no_innodb_table (非innodb表)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检table_static_expired (统计信息过期的表(长时间未更新统计信息))
[2022-09-21 16:08:48] [INFO]    [8827] 巡检fragment_table (碎片表)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检same_user_password (用户名和密码相同的账号)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检expired_password (密码过期的用户)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检any_host (未限制访问IP的账号)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检simple_password (密码简单的用户)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检innodb_buffer_stats_by_schema (各库内存使用情况)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检schema_object_overview (各库对象情况)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检memory_global_by_current_bytes (各事件内存使用)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检io_global_by_wait_by_latency (全局IO延迟)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检waits_global_by_latency (全局等待事件)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检schema_table_lock_waits (显示哪些会话在等待元数据锁时被阻塞)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检innodb_lock_waits (innodb锁等待)
[2022-09-21 16:08:48] [INFO]    [8827] 巡检master_info (主库相关信息(master info))
[2022-09-21 16:08:48] [INFO]    [8827] 巡检slave_info (从库相关信息(slave info))

**Comment by LeotLiu** [comment]
> 如果确定只有这个报错的话, 可以选择不巡检主从信息, 修改方法如下: 编辑配置文件conf/inspection.yaml 在 object_name : 'slave_info' 下面添加 enabled : False

关掉slave_info后，报其他错误了：
开始分析采集数据, 并生成巡检报告
Process Process-3:
Traceback (most recent call last):
  File "pandas/core/indexes/base.py", line 2898, in get_loc
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'MEMBER_STATE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "inspection/work_inspection.py", line 264, in inspection
  File "<string>", line 1, in <module>
  File "inspection/anadata.py", line 339, in mgr_info
  File "inspection/anadata.py", line 56, in __inner_function_3
  File "pandas/core/frame.py", line 2906, in __getitem__
  File "pandas/core/indexes/base.py", line 2900, in get_loc
KeyError: 'MEMBER_STATE'

**Comment by ddcw** [comment]
> > 如果确定只有这个报错的话, 可以选择不巡检主从信息, 修改方法如下: 编辑配置文件conf/inspection.yaml 在 object_name : 'slave_info' 下面添加 enabled : False
> 
> 关掉slave_info后，报其他错误了： 开始分析采集数据, 并生成巡检报告 Process Process-3: Traceback (most recent call last): File "pandas/core/indexes/base.py", line 2898, in get_loc File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item KeyError: 'MEMBER_STATE'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "multiprocessing/process.py", line 258, in _bootstrap File "multiprocessing/process.py", line 93, in run File "inspection/work_inspection.py", line 264, in inspection File "", line 1, in File "inspection/anadata.py", line 339, in mgr_info File "inspection/anadata.py", line 56, in __inner_function_3 File "pandas/core/frame.py", line 2906, in **getitem** File "pandas/core/indexes/base.py", line 2900, in get_loc KeyError: 'MEMBER_STATE'

看来是MGR信息中'MEMBER_STATE'有问题, 而且没有做异常处理, 临时解决办法同上:
编辑conf/inspection.yaml  在- object_name : 'mgr_info'下面添加 enabled : False

方便看下采集的XML文件中 slave_info 和 mgr_info 的样式么, 怀疑是这两处的格式不对(也可能是大小写问题).
一键生成巡检报告, 也就是直接使用ddcw_inspection采集并生成巡检报告  有没有类似问题呢?
