### ISSUE TITLE
任务一直处于巡检中，已经很长时间了

### ISSUE THREAD

**Issue by YanQinYuan** [ddcw/inspection#4]
centos环境

任务一直处于巡检中，已经很长时间了，状态是：

巡检slave_info (从库相关信息(slave info))

请问这是什么原因呢？谢谢~

**Comment by ddcw** [comment]
> centos环境
> 
> 任务一直处于巡检中，已经很长时间了，状态是：
> 
> 巡检slave_info (从库相关信息(slave info))
> 
> 请问这是什么原因呢？谢谢~

请确保巡检用户有执行 `show slave status;` 的权限.
授权"查看从库信息权限"命令参考: `grant replication client on *.* to 'username'@'%';`

巡检用户需要的完整权限如下:
`grant select on *.* to 'username'@'%';
grant replication client on *.* to 'username'@'%';
grant execute on *.* to 'username'@'%';`

**Comment by YanQinYuan** [comment]
感谢回复，以上权限已给。重新启动了一遍。

这个正常来说要巡检多久呢？

**Comment by YanQinYuan** [comment]
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "inspection/work_inspection.py", line 264, in inspection
  File "<string>", line 1, in <module>
  File "inspection/anadata.py", line 303, in slave_info
  File "pandas/core/frame.py", line 2912, in __getitem__
  File "pandas/core/indexing.py", line 1254, in _get_listlike_indexer
  File "pandas/core/indexing.py", line 1304, in _validate_read_indexer
KeyError: "['Retrieved_Gtid_Set', 'Executed_Gtid_Set', 'Master_Bind'] not in index"


这个怎么处理呢

**Comment by ddcw** [comment]
> Traceback (most recent call last): File "multiprocessing/process.py", line 258, in _bootstrap File "multiprocessing/process.py", line 93, in run File "inspection/work_inspection.py", line 264, in inspection File "", line 1, in File "inspection/anadata.py", line 303, in slave_info File "pandas/core/frame.py", line 2912, in **getitem** File "pandas/core/indexing.py", line 1254, in _get_listlike_indexer File "pandas/core/indexing.py", line 1304, in _validate_read_indexer KeyError: "['Retrieved_Gtid_Set', 'Executed_Gtid_Set', 'Master_Bind'] not in index"
> 
> 这个怎么处理呢

1. 默认是巡检30秒, 可以在配置文件里面修改(data_collection_time : 30)

2. 该报错为 show slave status 中无 Retrieved_Gtid_Set Executed_Gtid_Set Master_Bind. (对于不同的版本,不同的参数可能没得这些值, 请确认mysql版本是否为5.7或者8.0.  也可以手动执行`show slave status`看下有没得Retrieved_Gtid_Set之类的). 


解决办法: 禁用slave巡检即可.   修改配置文件 `conf/inspection.yaml` 中的slave_info项, 新增个 `enabled : False` 意思是不巡检这一项
例子:
```
.....其它省略
  - object_name : 'slave_info'
    enabled : False
    des : '从库相关信息(slave info)'
    sql : 'select 1;'
    score : 5
    type : 3
    opt : 0
.....其它省略
```

**Comment by YanQinYuan** [comment]
感谢回复。按上面的要求修改后，没有卡在slave_info这一步，然后卡在下面这一步：

巡检mgr_info (MGR集群相关)

Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "inspection/work_inspection.py", line 264, in inspection
  File "<string>", line 1, in <module>
  File "inspection/anadata.py", line 343, in mgr_info
AttributeError: 'DatabaseError' object has no attribute 'shape'

ps:数据库：10.3.9-MariaDB-1:10.3.9+maria~bionic-log

**Comment by ddcw** [comment]
本项目主要是针对mysql5.7/8.0设计的,  不建议用来巡检mariadb.
解决办法:    和slave_info是一样的,  在配置文件里面给mgr_info加个 enabled : False 
注: 某个巡检项有问题, 都可以不巡检该项(enabled : False ).

**Comment by YanQinYuan** [comment]
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "inspection/work_inspection.py", line 264, in inspection
  File "<string>", line 1, in <module>
  File "inspection/anadata.py", line 343, in mgr_info
AttributeError: 'DatabaseError' object has no attribute 'shape'

按上面的加了enabled : False，但还是卡在mgr_info，然后有这个报错

**Comment by ddcw** [comment]
> Traceback (most recent call last): File "multiprocessing/process.py", line 258, in _bootstrap File "multiprocessing/process.py", line 93, in run File "inspection/work_inspection.py", line 264, in inspection File "", line 1, in File "inspection/anadata.py", line 343, in mgr_info AttributeError: 'DatabaseError' object has no attribute 'shape'
> 
> 按上面的加了enabled : False，但还是卡在mgr_info，然后有这个报错

按理说禁用之后,就不会执行这一段代码啊,   'mgr_info'里面原来就有个 enabled:True  你直接修改这个就行. 
你是直接在后面新增的, 还是在原来的那里修改的呢?

**Comment by YanQinYuan** [comment]
解决了，谢谢~
