### ISSUE TITLE
巡检日志一致卡在巡检innodb_log_buffer_size (redo缓存大小)，版本是8.0.30

### ISSUE THREAD

**Issue by zhj0523** [ddcw/inspection#5]
报错如下：巡检日志一致卡在巡检innodb_log_buffer_size (redo缓存大小)，mysql的版本是8.0.30，我把8.0.30中丢弃的参数innodb_log_file_size和innodb_log_files_in_group禁止了也没什么用。。

```进度:0/1
进度:0/1
进度:0/1
进度:0/1
进度:0/1
进度:0/1
进度:0/1
进度:0/1
进度:0/1
进度:0/1
Process Process-3:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "inspection/work_inspection.py", line 331, in inspection
AttributeError: 'DatabaseError' object has no attribute 'values'
进度:0/1
进度:0/1
进度:0/1
进度:0/1
进度:0/1
进度:0/1
进度:0/1
进度:0/1

**Comment by ddcw** [comment]
> 报错如下：巡检日志一致卡在巡检innodb_log_buffer_size (redo缓存大小)，mysql的版本是8.0.30，我把8.0.30中丢弃的参数innodb_log_file_size和innodb_log_files_in_group禁止了也没什么用。。
> 
> ```
> 进度:0/1
> 进度:0/1
> 进度:0/1
> 进度:0/1
> 进度:0/1
> 进度:0/1
> 进度:0/1
> 进度:0/1
> 进度:0/1
> Process Process-3:
> Traceback (most recent call last):
>   File "multiprocessing/process.py", line 258, in _bootstrap
>   File "multiprocessing/process.py", line 93, in run
>   File "inspection/work_inspection.py", line 331, in inspection
> AttributeError: 'DatabaseError' object has no attribute 'values'
> 进度:0/1
> 进度:0/1
> 进度:0/1
> 进度:0/1
> 进度:0/1
> 进度:0/1
> 进度:0/1
> 进度:0/1
> ```

这个报错是 采集的mysql内存失败, 相关sql为`select * from sys.memory_global_total`. 你可以手动查询该视图看下报错. 预计报错原因如下:
1. 无视图sys.memory_global_total   重建该视图即可
2. 该视图使用的函数为: sys.format_bytes,  部分环境可能无此函数(导数据的锅....).   重建该函数即可
3. 权限问题
