### ISSUE TITLE
巡检一直卡在：分析节点关系中，wait......

### ISSUE THREAD

**Issue by tytanyi** [ddcw/inspection#6]
![image](https://github.com/ddcw/inspection/assets/86992361/ba058d28-876e-4e1d-a606-25ee0ddae366)
巡检一直卡在：分析节点关系中，wait......
html 文件生成后一直卡在分析节点关系中，测试的节点是单节点，并没有主从

**Comment by tytanyi** [comment]
然后就一直换行，没有输出任何内容，手动ctrl+C 后输出如下：
^CTraceback (most recent call last):
  File "main.py", line 50, in <module>
  File "inspection/cmd_console.py", line 166, in run
KeyboardInterrupt
[40344] Failed to execute script 'main' due to unhandled exception!
Process Process-4:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "inspection/work_inspection.py", line 57, in inspection
  File "<string>", line 2, in get
  File "multiprocessing/managers.py", line 757, in _callmethod
  File "multiprocessing/connection.py", line 254, in recv
  File "multiprocessing/connection.py", line 411, in _recv_bytes
  File "multiprocessing/connection.py", line 383, in _recv
KeyboardInterrupt
Process Process-3:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "inspection/work_inspection.py", line 57, in inspection
  File "<string>", line 2, in get
  File "multiprocessing/managers.py", line 757, in _callmethod
  File "multiprocessing/connection.py", line 254, in recv
  File "multiprocessing/connection.py", line 411, in _recv_bytes
  File "multiprocessing/connection.py", line 383, in _recv
KeyboardInterrupt
Process Process-6:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "inspection/work_relation.py", line 23, in relation
  File "<string>", line 2, in get
  File "multiprocessing/managers.py", line 757, in _callmethod
  File "multiprocessing/connection.py", line 254, in recv
  File "multiprocessing/connection.py", line 411, in _recv_bytes
  File "multiprocessing/connection.py", line 383, in _recv
KeyboardInterrupt
Process Process-5:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "inspection/work_inspection.py", line 57, in inspection
  File "<string>", line 2, in get
  File "multiprocessing/managers.py", line 757, in _callmethod
  File "multiprocessing/connection.py", line 254, in recv
  File "multiprocessing/connection.py", line 411, in _recv_bytes
  File "multiprocessing/connection.py", line 383, in _recv
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "multiprocessing/util.py", line 262, in _run_finalizers
  File "multiprocessing/util.py", line 186, in __call__
  File "multiprocessing/managers.py", line 809, in _decref
  File "multiprocessing/connection.py", line 491, in Client
  File "multiprocessing/connection.py", line 618, in SocketClient
KeyboardInterrupt

**Comment by ddcw** [comment]
巡检报告生成了卅.  
看起来是没有判断节点数量, 直接就分析主从关系了.....
可以在配置文件里面 注释掉 节点关系分析功能
编辑`conf/global.yaml` 修改node_relation 值为 False
