### ISSUE TITLE
666感谢作者，思路很棒。不过我巡检mariadb也遇到了个问题，提示ZeroDivisionDrror is not JSON resi

### ISSUE THREAD

**Issue by heartgon** [ddcw/inspection#8]
[2024-03-08 07:21:22,317] ERROR in app: Exception on /inspection_status [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1716, in make_response
    rv = jsonify(rv)
  File "/usr/local/lib/python3.6/site-packages/flask/json/__init__.py", line 361, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/usr/local/lib/python3.6/site-packages/flask/json/__init__.py", line 139, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/site-packages/flask/json/__init__.py", line 57, in default
    return super().default(o)
  File "/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ZeroDivisionError' is not JSON serializable
10.30.20.169 - - [2024-03-08 07:21:22] "POST /inspection_status HTTP/1.1" 500 426 0.001134

请问该怎么处理?

**Comment by ddcw** [comment]
> [2024-03-08 07:21:22,317] ERROR in app: Exception on /inspection_status [POST] Traceback (most recent call last): File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app response = self.full_dispatch_request() File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1519, in full_dispatch_request return self.finalize_request(rv) File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1538, in finalize_request response = self.make_response(rv) File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1716, in make_response rv = jsonify(rv) File "/usr/local/lib/python3.6/site-packages/flask/json/**init**.py", line 361, in jsonify f"{dumps(data, indent=indent, separators=separators)}\n", File "/usr/local/lib/python3.6/site-packages/flask/json/**init**.py", line 139, in dumps rv = _json.dumps(obj, **kwargs) File "/usr/lib64/python3.6/json/**init**.py", line 238, in dumps **kw).encode(obj) File "/usr/lib64/python3.6/json/encoder.py", line 199, in encode chunks = self.iterencode(o, _one_shot=True) File "/usr/lib64/python3.6/json/encoder.py", line 257, in iterencode return _iterencode(o, 0) File "/usr/local/lib/python3.6/site-packages/flask/json/**init**.py", line 57, in default return super().default(o) File "/usr/lib64/python3.6/json/encoder.py", line 180, in default o.**class**.**name**) TypeError: Object of type 'ZeroDivisionError' is not JSON serializable 10.30.20.169 - - [2024-03-08 07:21:22] "POST /inspection_status HTTP/1.1" 500 426 0.001134
> 
> 请问该怎么处理?

这个是有些值为0, 然后做除法的时候就报错了. 好像不影响巡检报告生成吧我记得, 你看下 tmp目录下面有没得巡检报告呢.
注:这个含有图形化的版本后面不会更新了.   下一个版本是 纯shell版的.

**Comment by heartgon** [comment]
有报告，哈哈，nice

**Comment by heartgon** [comment]
直接运行源码，发现有些module缺失。建议源码里面加个requirements.txt，方便调试

pyyaml
paramiko
pymysql
pandas
docx
python-docx
gevent
flask
